### ISSUE TITLE
tslint (configuration) issues

### ISSUE THREAD

**Issue by developer-lindner** [TypeStrong/fork-ts-checker-webpack-plugin#106]
Seems like setting **tslint: true** exceeds maximum call stack very soon.
Activating it stops notifications by fork-ts-checker-notifier-webpack-plugin as well.

Also notification stops in watch mode?!

**Comment by johnnyreilly** [comment]
What happens if you tweak the `memoryLimit` option? Does that help?

**Comment by developer-lindner** [comment]
@johnnyreilly Does it work for you? I mean does it notify about tslint issues?
Just noticed success or failed build notifications (which are coming from ts check) but no tslint message at all?!

settings:

```
new ForkTsCheckerWebpackPlugin({
    checkSyntacticErrors: true,
    tsconfig: path.resolve(__dirname, 'tsconfig.json'),
    tslint: true,
    memoryLimit: 1024
}),

new ForkTsCheckerNotifierWebpackPlugin({
    alwaysNotify: true
}),
```

Doesn't work in watch mode?

Error Message (even with memoryLimit):
```
RangeError: Maximum call stack size exceeded
    at Object.flatMap (/node_modules/tslint/lib/utils.js:151:18)
    at Linter.getAllFailures (/node_modules/tslint/lib/linter.js:139:32)
    at Linter.lint (/node_modules/tslint/lib/linter.js:99:33)
    at /node_modules/fork-ts-checker-webpack-plugin/lib/IncrementalChecker.js:150:30
    at WorkSet.forEach (/node_modules/fork-ts-checker-webpack-plugin/lib/WorkSet.js:17:13)
    at IncrementalChecker.getLints (/node_modules/fork-ts-checker-webpack-plugin/lib/IncrementalChecker.js:147:17)
    at run (/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:15:29)
    at process.<anonymous> (/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:38:5)
    at process.emit (events.js:159:13)
    at emit (internal/child_process.js:790:12)
```

tslint.json:
```
{
    "defaultSeverity": "warning",
    "extends": ["tslint:latest", "tslint-react", "tslint-eslint-rules"],
    "rules": {

        /* tslint https://palantir.github.io/tslint/rules/ */
        "array-type": [true, "generic"],
        "arrow-parens": false,
        "eofline": false,
        "max-classes-per-file": [true, 10],
        "max-file-line-count": [true, 666],
        "max-line-length": [false],
        "member-access": [true, "check-accessor", "check-constructor"],
        "member-ordering": [
            true,
            { "order": "fields-first" }
        ],
        "no-consecutive-blank-lines": [true, 1],
        "no-debugger": false,
        "no-implicit-dependencies": false,
        "no-submodule-imports": false,
        "no-trailing-whitespace": true,
        "no-unused-variable": true,
        "no-var-requires": false,
        "object-literal-sort-keys": false,
        "only-arrow-functions": [true],
        "ordered-imports": [false],
        "trailing-comma": [false],
        "triple-equals": [false],
        "variable-name": [
            true,
            "ban-keywords",
            "check-format",
            "allow-leading-underscore"
        ],

        /* tslint-react https://github.com/palantir/tslint-react */
        "jsx-no-multiline-js": false,
        "jsx-self-close": true,


        /* tslint-eslint-rules https://github.com/buzinas/tslint-eslint-rules */
        "no-multi-spaces": true,
        "object-curly-spacing": "always",
        "ter-max-len": [
            true,
            160,
            {
                "ignoreComments": true
            }
        ]
    }
}
```

**Comment by developer-lindner** [comment]
**watch: path.resolve(__dirname, "module")** => 1400+ *.ts(x) files

seems to help (which reduces files amount i guess), but still as long as **tslint: true** is set:
no notifications at all...

**Comment by johnnyreilly** [comment]
Give me an hour or so - I'll see if I can try something

**Comment by johnnyreilly** [comment]
See this: https://github.com/johnnyreilly/fork-ts-checker-demo

Seems to work okay?
