### ISSUE TITLE
Fails to compile when used with tslint

### ISSUE THREAD

**Issue by jprince** [TypeStrong/fork-ts-checker-webpack-plugin#125]
With `tslint: true` I get the following error:
```
/Users/josh/DEV/censinet/client/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:424
            this.compiler.hooks.forkTsCheckerReceive.call(this.diagnostics, this.lints);
                                                    ^

TypeError: Cannot read property 'call' of undefined
    at ForkTsCheckerWebpackPlugin.handleServiceMessage (/Users/josh/DEV/censinet/client/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:424:53)
    at ChildProcess.<anonymous> (/Users/josh/DEV/censinet/client/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:382:70)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Seems to affect all fork-ts-checker-webpack-plugin versions >= 0.4.0
Webpack 4.12.0
ts-loader 4.4.1
tslint 5.10

**Comment by jprince** [comment]
Error does not seem to exist with:
fork-ts-checker-webpack-plugin 0.4.2
Webpack 3.7.1
ts-loader 2.3.7
tslint 5.10

**Comment by johnnyreilly** [comment]
I don't experience this error myself - and I'm using the setup you describe...

**Comment by jprince** [comment]
Hmm ok. As soon as I have some time I'll take a crack at setting up a demo.

**Comment by thavlik** [comment]
I am having this issue as well.

webpack 4.19.0
ts-loader 5.1.0
happypack 5.0.0
fork-ts-checker-webpack-plugin 0.4.9
No tslint

So it appears that between ForkTsCheckerWebpackPlugin.prototype's registerCustomHooks and handleServiceMessage, all of the custom hooks registered in this.compiler.hooks become undefined.

this.compiler is the same compiler in both of those methods (i.e. sanity check is passed). I can't find anything blatantly wrong in index.js that would be causing this - no explicit assignment to undefined or calls to delete are causing this occur.

**Comment by codingwesley** [comment]
```
/Users/chenhuan/QuietWind/react-fe-learning/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:427
            this.compiler.hooks.forkTsCheckerReceive.call(this.diagnostics, this.lints);
                                                     ^
TypeError: Cannot read property 'call' of undefined
    at ForkTsCheckerWebpackPlugin.handleServiceMessage (/Users/chenhuan/QuietWind/react-fe-learning/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:427:54)
    at ChildProcess.<anonymous> (/Users/chenhuan/QuietWind/react-fe-learning/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:382:70)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

demo address: https://github.com/QwChat/react-fe-learning


@johnnyreilly  hope will help you
