### ISSUE TITLE
Does it work with TypeScript 3?

### ISSUE THREAD

**Issue by martpie** [TypeStrong/fork-ts-checker-webpack-plugin#153]
Hello 👋

I have a Next.JS application using TypeScript and `fork-ts-checker-webpack-plugin` to do type-checking. I am not sure if this is a problem related to Next.JS or this module.

When using TypeScript 3, I got the following error when trying to start my app:

```
/Users/pierre/dev/project/src/frontend/packages/web/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:22
        throw error;
        ^

TypeError: Cannot read property 'charCodeAt' of undefined
    at isLateBoundName (/Users/pierre/dev/project/src/frontend/packages/web/node_modules/typescript/lib/typescript.js:34687:25)
    at createUnionOrIntersectionProperty (/Users/pierre/dev/project/src/frontend/packages/web/node_modules/typescript/lib/typescript.js:35741:38)
    at getUnionOrIntersectionProperty (/Users/pierre/dev/project/src/frontend/packages/web/node_modules/typescript/lib/typescript.js:35807:28)
    at getPropertyOfUnionOrIntersectionType (/Users/pierre/dev/project/src/frontend/packages/web/node_modules/typescript/lib/typescript.js:35815:28)
    at getPropertyOfType (/Users/pierre/dev/project/src/frontend/packages/web/node_modules/typescript/lib/typescript.js:35844:24)
    at checkVariableLikeDeclaration (/Users/pierre/dev/project/src/frontend/packages/web/node_modules/typescript/lib/typescript.js:51326:36)
    at checkBindingElement (/Users/pierre/dev/project/src/frontend/packages/web/node_modules/typescript/lib/typescript.js:51434:20)
    at checkSourceElement (/Users/pierre/dev/project/src/frontend/packages/web/node_modules/typescript/lib/typescript.js:53432:28)
    at Object.forEach (/Users/pierre/dev/project/src/frontend/packages/web/node_modules/typescript/lib/typescript.js:209:30)
    at checkVariableLikeDeclaration (/Users/pierre/dev/project/src/frontend/packages/web/node_modules/typescript/lib/typescript.js:51338:20)
```

Do you have any idea what could cause this?

**Comment by martpie** [comment]
After doing some research, it appears that it may be related to the project configuration itself, I'll investigate.

**Comment by martpie** [comment]
It seems to be a problem with TypeScript itself, with a function return type which is an union type. I really don't get it.

Anyway, unrelated to this repo.

_edit: found it: https://github.com/Microsoft/TypeScript/issues/26321_
