### ISSUE TITLE
Cannot read property 'call' of undefined?

### ISSUE THREAD

**Issue by Adherentman** [TypeStrong/fork-ts-checker-webpack-plugin#161]
I don't know what caused this problem.

version:
- webpack ^4.20.2
- fork-ts-checker-webpack-plugin ^0.4.9
- ts-loader ^5.2.1
- cache-loader ^1.2.2
- thread-loader ^1.2.0

*this is my config*:

```javascript
const path = require('path');
const os = require('os');
const webpack = require('webpack');
const HtmlWebpacPlugin = require('html-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
// const WebpackDeepScopeAnalysisPlugin = require('webpack-deep-scope-plugin')
// 	.default;
const SpeedMeasurePlugin = require('speed-measure-webpack-plugin');

const devMode = process.env.NODE_ENV !== 'production';

const HtmlPlugin = new HtmlWebpacPlugin({
	template: path.resolve(__dirname, './index.html'),
	title: 'xxxx',
	favicon: './favicon.ico',
});

const CleanDistPlugin = new CleanWebpackPlugin(['cms2'], {
	root: '/project/dist/interface/www/',
	verbose: true,
});

const extractSassPlugin = new MiniCssExtractPlugin({
	filename: devMode ? 'css/[name].css' : 'css/[name].[hash].css',
	chunkFilename: devMode ? 'css/[name].css' : 'css/[name].[hash].css',
});

const smp = new SpeedMeasurePlugin();

module.exports = smp.wrap({
	context: path.resolve(process.cwd()),
	entry: './src/index.tsx',
	output: {
		path: path.resolve(__dirname, '../../../dist/interface/www/cms2'),
		publicPath: '/cms2/',
		filename: './scripts/[name].[hash].js',
		chunkFilename: './scripts/[name].[hash].js',
	},
	resolve: {
		extensions: ['.ts', '.tsx', '.js', '.jsx'],
	},
	module: {
		rules: [
			{
				test: /\.tsx?$/,
				use: [
					{ loader: 'cache-loader' },
					{
						loader: 'thread-loader',
						options: {
							workers: require('os').cpus().length - 1,
						},
					},
					{
						loader: 'ts-loader',
						options: {
							happyPackMode: true,
						},
					},
				],
				exclude: path.resolve(process.cwd(), 'node_modules'),
			},
			{
				test: /\.scss$/,
				use: [
					MiniCssExtractPlugin.loader,
					{
						loader: 'css-loader',
						options: {
							modules: true,
							importLoader: 2,
						},
					},
					'sass-loader',
				],
			},
			{
				test: /\.(png|svg|jpg|gif)$/,
				use: [
					{
						loader: 'file-loader',
						options: {
							name: devMode ? 'images/[name].[ext]' : 'images/[hash].[ext]',
						},
					},
				],
			},
		],
	},
	plugins: [
		HtmlPlugin,
		CleanDistPlugin,
		extractSassPlugin,
		new ForkTsCheckerWebpackPlugin({ checkSyntacticErrors: true }),
		// new WebpackDeepScopeAnalysisPlugin(),
	],
});

```

*this is terminal log*:

```shell
/project/interface/www/cms2/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:424             
            this.compiler.hooks.forkTsCheckerReceive.call(this.diagnostics, this.lints);            
                                                     ^                                               
                                                                                                     
TypeError: Cannot read property 'call' of undefined                                                  
    at ForkTsCheckerWebpackPlugin.handleServiceMessage (/project/interface/www/cms2/node_modules/fork-│
ts-checker-webpack-plugin/lib/index.js:424:54)                                                       
    at ChildProcess.<anonymous> (/project/interface/www/cms2/node_modules/fork-ts-checker-webpack-plug│
in/lib/index.js:382:70)                                                                              
    at ChildProcess.emit (events.js:182:13)                                                          
    at emit (internal/child_process.js:811:12)                                                       
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

*what can i do*?

**Comment by johnnyreilly** [comment]
It might be worth you comparing your setup with a working example: https://github.com/TypeStrong/ts-loader/tree/master/examples/thread-loader

**Comment by Adherentman** [comment]
@johnnyreilly thanks, i copy this example, But this problem still exists

**Comment by charlesbetros** [comment]
Is this the same as #170? If so Speed Measure Plugin seems to be causing this. Works fine without the 'smp.wrap' (for me).
