### ISSUE TITLE
Error: Cannot find module 'lodash.isstring'

### ISSUE THREAD

**Issue by yoyo837** [TypeStrong/fork-ts-checker-webpack-plugin#178]
```
Error: Cannot find module 'lodash.isstring'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:8:16)
```

**Comment by johnnyreilly** [comment]
I think you just need to reinstall your packages.

See https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/175

**Comment by yoyo837** [comment]
Thanks for your reply.
