### ISSUE TITLE
Receiving error on startup in webpack -Expected diagnostics to start

### ISSUE THREAD

**Issue by kelly-tock** [TypeStrong/fork-ts-checker-webpack-plugin#185]
/Users/kelly/dashboard/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:22
        throw error;
        ^

Error: Expected diagnostics to have start
    at createFromDiagnostic (/Users/kelly/dashboard/node_modules/fork-ts-checker-webpack-plugin/lib/NormalizedMessage.js:22:23)
    at Array.map (<anonymous>)
    at IncrementalChecker.getDiagnostics (/Users/kelly/dashboard/node_modules/fork-ts-checker-webpack-plugin/lib/IncrementalChecker.js:147:78)
    at run (/Users/kelly/dashboard/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:13:31)
    at process.on.message (/Users/kelly/dashboard/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:38:5)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

was working a bit ago, i've uninstalled the modules and re-installed. node 10.12. webpack 4.8.2. 

any thoughts?

**Comment by johnnyreilly** [comment]
We've just changed to use es6 code rather than es5 code with 0.5.0... but given you're on node 10 that should be fine...

https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/master/CHANGELOG.md

**Comment by kelly-tock** [comment]
downgrading to before `0.5.0` is working. we are compiling `node_modules` as well, maybe that is the issue. i'll try excluding this package.

**Comment by kelly-tock** [comment]
that was it. 
```
{
      test: /\.js$/,
      exclude: [/@babel(?:\/|\\{1,2})runtime/, /fork-ts-checker-webpack-plugin/],
      use: [
        {
          loader: 'babel-loader',
          options: {
            cacheDirectory: true,
            cacheCompression: false,
            compact: false,
            plugins: ['@babel/plugin-syntax-dynamic-import'],
            presets: ['@babel/preset-env'],
          },
        },
      ],
    },
```

we are doing this to account for some modules switching to only es6 code to support older browswers.
