### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bknill** [TypeStrong/fork-ts-checker-webpack-plugin#197]
I use Create React App, I'm not sure where this is coming from but after a recent Typescript update this plugin is throwing this error and stopping the development server. 

```
C:\workspace\client\client\node_modules\fork-ts-checker-webpack-plugin-alt\lib\service.js:22
        throw error;

  at Object.getDeclarationOfKind (C:\workspace\client\client\node_modules\typescript\lib\typescript.js:8107:34)
    at getConstraintDeclaration (C:\workspace\client\client\node_modules\typescript\lib\typescript.js:38272:42)
    at getConstraintFromTypeParameter (C:\workspace\client\client\node_modules\typescript\lib\typescript.js:38327:49)
    at fillMissingTypeArguments (C:\workspace\client\client\node_modules\typescript\lib\typescript.js:37877:49)
    at getTypeFromClassOrInterfaceReference (C:\workspace\client\client\node_modules\typescript\lib\typescript.js:38429:78)
    at getTypeReferenceTypeWorker (C:\workspace\client\client\node_modules\typescript\lib\typescript.js:38559:24)
    at getTypeReferenceType (C:\workspace\client\client\node_modules\typescript\lib\typescript.js:38492:24)
    at getTypeFromTypeReference (C:\workspace\client\client\node_modules\typescript\lib\typescript.js:38671:28)
    at getTypeFromTypeNode (C:\workspace\client\client\node_modules\typescript\lib\typescript.js:40178:28)
    at getConstraintFromTypeParameter (C:\workspace\client\client\node_modules\typescript\lib\typescript.js:38328:72)
```

Here is a basic tsconfig

```
> {
>   "compilerOptions": {
>     "allowJs": true,
>     "skipLibCheck": false,
>     "esModuleInterop": true,
>     "allowSyntheticDefaultImports": true,
>     "strict": true,
>     "forceConsistentCasingInFileNames": true,
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "noEmit": true,
>     "jsx": "preserve",
>     "target": "es5",
>     "module": "esnext",
>     "moduleResolution": "node"
>   },
>   "include": [
>     "src"
>   ]
> }
```

If I change the include to a folder with no Typescript it runs fine.. any clues?

**Comment by johnnyreilly** [comment]
I don't know I'm afraid. If you try upping the `memoryLimit` from `2048` in the options does that fix it?

**Comment by TeamDman** [comment]
I believe it was an issue with typescript that is [now fixed.](https://github.com/Microsoft/TypeScript/issues/28785)
Try updating TS if you have the issue.

Related: https://github.com/vuejs/vue-cli/issues/2019
