### ISSUE TITLE
TypeError: lint.getRuleSeverity is not a function

### ISSUE THREAD

**Issue by Toilal** [TypeStrong/fork-ts-checker-webpack-plugin#20]
I just upgraded my dependencies, and it now display this stacktrace.

```
/usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:30
    throw error;
    ^

TypeError: lint.getRuleSeverity is not a function
    at NormalizedMessage.createFromLint (/usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/NormalizedMessage.js:42:20)
    at Array.map (native)
    at IncrementalChecker.getLints (/usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/IncrementalChecker.js:187:11)
    at run (/usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:23:23)
    at process.<anonymous> (/usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:47:3)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:753:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by piotr-oles** [comment]
I will check this out :) Please send me your tslint version and tslint.json file to help reproduce the bug :)

**Comment by Toilal** [comment]
Sorry, I was using old version of this plugin, after upgrading to `0.2.2` issue has gone.
