### ISSUE TITLE
typescript errors on `moduleResolution` with `useTypescriptIncrementalApi: true`

### ISSUE THREAD

**Issue by zackschuster** [TypeStrong/fork-ts-checker-webpack-plugin#245]
[relevant config](https://github.com/zackschuster/configs/blob/master/webpack.merge.js)

`fork-ts-checker`: 1.2.0
`ts-loader`: 5.3.3
`typescript`: 3.4.4

error text:
```
INTERNAL ERROR: Debug Failure. Unexpected moduleResolution: node
stack trace:
Error: Debug Failure. Unexpected moduleResolution: node
    at Object.resolveModuleName (/Users/zschuster/source/CCTC/node_modules/typescript/lib/typescript.js:26596:37)
    at resolveModuleName (/Users/zschuster/source/CCTC/node_modules/typescript/lib/typescript.js:91854:36)
    at resolveNamesWithLocalCache (/Users/zschuster/source/CCTC/node_modules/typescript/lib/typescript.js:91906:38)
    at Object.resolveModuleNames (/Users/zschuster/source/CCTC/node_modules/typescript/lib/typescript.js:91956:20)
    at Object.resolveModuleNames (/Users/zschuster/source/CCTC/node_modules/typescript/lib/typescript.js:93211:112)
    at resolveModuleNamesWorker (/Users/zschuster/source/CCTC/node_modules/typescript/lib/typescript.js:88318:127)
    at resolveModuleNamesReusingOldState (/Users/zschuster/source/CCTC/node_modules/typescript/lib/typescript.js:88560:24)
    at processImportedModules (/Users/zschuster/source/CCTC/node_modules/typescript/lib/typescript.js:89890:35)
    at findSourceFile (/Users/zschuster/source/CCTC/node_modules/typescript/lib/typescript.js:89694:17)
    at /Users/zschuster/source/CCTC/node_modules/typescript/lib/typescript.js:89548:85
```

manually setting the `moduleResolution` in `CompilerHost` removes the error, though it does break typescript lib detection:

```
ERROR in undefined(undefined,undefined):
TS6053: File '/Users/zschuster/source/CCTC/node_modules/typescript/lib/dom.ts' not found.
ERROR in undefined(undefined,undefined):
TS6053: File '/Users/zschuster/source/CCTC/node_modules/typescript/lib/es2017.ts' not found.
```

this is the best i've been able to find so far; not sure what else to do if i want the feature.

**Comment by johnnyreilly** [comment]
If you provide a minimal repro repo that would help someone look into the issue

**Comment by zackschuster** [comment]
working on getting a repro together :)
