### ISSUE TITLE
TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by JasonIsGithubbin** [TypeStrong/fork-ts-checker-webpack-plugin#259]
```
TypeError: Cannot read property 'options' of undefined
    at ForkTsCheckerWebpackPlugin.computeContextPath (node_modules/fork-ts-checker-webpack-plugin/lib/index.js:31:41)
    at ForkTsCheckerWebpackPlugin.instance.(anonymous function) [as computeContextPath] (node_modules/grunt-webpack/src/options/OptionHelper.js:88:35)
    at ForkTsCheckerWebpackPlugin.apply (node_modules/fork-ts-checker-webpack-plugin/lib/index.js:133:34)
    at webpack (node_modules/webpack/lib/webpack.js:47:13)
```

**Comment by johnnyreilly** [comment]
Closing as insufficient information
