### ISSUE TITLE
Fork ts checker crashes without any details

### ISSUE THREAD

**Issue by ankitrg** [TypeStrong/fork-ts-checker-webpack-plugin#35]
```
Happy[ts]: All set; signaling webpack to proceed.
Starting type checking service...
Using 1 worker with 2048MB memory limit
Watching:
/home/aks/advertkit/app/javascript
/home/aks/advertkit/app/views
/home/aks/advertkit/app/assets/stylesheets
/home/aks/advertkit/app/assets/images
/home/aks/advertkit/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:30
    throw error;
    ^

Error: Debug Failure. 
    at typeToString (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:28777:22)
    at reportRelationError (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:34714:34)
    at isRelatedTo (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:34860:21)
    at checkTypeRelatedTo (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:34697:26)
    at checkApplicableSignature (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:40608:26)
    at resolveCall (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:41011:17)
    at resolveCallExpression (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:41163:20)
    at resolveSignature (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:41398:28)
    at getResolvedSignature (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:41430:26)
    at checkCallExpression (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:41479:29)
ts-loader: Using typescript@2.4.1 and /home/aks/advertkit/tsconfig.json
ts-loader: Using typescript@2.4.1 and /home/aks/advertkit/tsconfig.json

```

Can anyone help me why this is happening or how I can dubug this?

**Comment by piotr-oles** [comment]
It's error from typescript - you can create issue on typescript's repo. There is probably some case in your code that typescript can't handle.

**Comment by ankitrg** [comment]
Thanks, I'll do that.
