### ISSUE TITLE
Nesting tsconfig inside a subdirectory causes an error parsing even though tsc on it's own works fine.

### ISSUE THREAD

**Issue by afgriffiths** [TypeStrong/fork-ts-checker-webpack-plugin#367]
## Current behavior
When nesting `tsconfig.json` inside a subdirectory of the project, an error occurs when trying to parse `tsconfig.json`. Here is the fill stack trace:

```
App threw an error during load
Error: Module build failed (from /home/adamfg/workplace/Boost/node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json
    at Object.loader (/home/adamfg/workplace/Boost/node_modules/ts-loader/dist/index.js:19:18)
    at Object../src/main.ts (/home/adamfg/workplace/Boost/.webpack/main/index.js:97:7)
    at __webpack_require__ (/home/adamfg/workplace/Boost/.webpack/main/index.js:21:30)
    at /home/adamfg/workplace/Boost/.webpack/main/index.js:85:18
    at Object.<anonymous> (/home/adamfg/workplace/Boost/.webpack/main/index.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
```

## Expected behavior
`tsconfig.json` should be parsed without an error. 

## Steps to reproduce the issue
Run the following commands:

```
git clone --single-branch --branch backup/afgriffiths https://github.com/afgriffiths/Boost.git
git checkout 6b283fa8a1ab8b07c4dffddb9527183800dc5bde
npm install
npm start
```

If you then run the following commands:
```
cd cfg
tsc
```
you will see `tsc` executes without errors

## Issue reproduction repository
https://github.com/afgriffiths/Boost/tree/backup/afgriffiths

This repository is simply a fork of [this repository](https://github.com/euZebe/electron-react-ts-boilerplate) with some of the config files moved inside the `cfg` directory.

## Environment
 - **fork-ts-checker-webpack-plugin**: 3.1.1
 - **typescript**: 3.7.3
 - **tslint**: N/A
 - **webpack**: N/A (uses @electron-forge/plugin-webpack 6.0.0-beta.46)
 - **os**: Ubuntu 18.04.3

**Comment by piotr-oles** [comment]
Thank you for reporting this issue. I've tried to reproduce it, and after commenting out `ForkTsCheckerWebpackPlugin`, the error still throws. It seems that the issue is in the `ts-loader` - please report this issue there :)
