### ISSUE TITLE
incompatible with Webpack 5.0

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/fork-ts-checker-webpack-plugin#383]
With Webpack 5.0, we get an error, because `hooks` is no longer extensible:

```
TypeError: Cannot add property forkTsCheckerServiceBeforeStart, object is not extensible
    at ForkTsCheckerWebpackPlugin.registerCustomHooks (/home/trusktr/src/velodyne_sw+vella-frontend-projects/apps/mapper-annotator/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:212:61)
    at ForkTsCheckerWebpackPlugin.apply (/home/trusktr/src/velodyne_sw+vella-frontend-projects/apps/mapper-annotator/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:117:22)
    at createCompiler (/home/trusktr/src/velodyne_sw+vella-frontend-projects/apps/mapper-annotator/node_modules/webpack/lib/webpack.js:65:12)
    at webpack (/home/trusktr/src/velodyne_sw+vella-frontend-projects/apps/mapper-annotator/node_modules/webpack/lib/webpack.js:94:14)
    at processOptions (/home/trusktr/src/velodyne_sw+vella-frontend-projects/apps/mapper-annotator/node_modules/webpack-cli/bin/cli.js:272:16)
    at /home/trusktr/src/velodyne_sw+vella-frontend-projects/apps/mapper-annotator/node_modules/webpack-cli/bin/cli.js:364:3
    at Object.parse (/home/trusktr/src/velodyne_sw+vella-frontend-projects/apps/mapper-annotator/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/trusktr/src/velodyne_sw+vella-frontend-projects/apps/mapper-annotator/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/trusktr/src/velodyne_sw+vella-frontend-projects/apps/mapper-annotator/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/trusktr/src/velodyne_sw+vella-frontend-projects/apps/mapper-annotator/node_modules/webpack/bin/webpack.js:127:2)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by piotr-oles** [comment]
@trusktr
Please try [fork-ts-checker-webpack-plugin@alpha](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha) - I've published a new version which should resolve this issue 🚀
I will close this issue to clean-up the backlog. If this release didn't solve the issue, we can re-open this :)
