### ISSUE TITLE
No handler found for procedure getIssues

### ISSUE THREAD

**Issue by jvvcn** [TypeStrong/fork-ts-checker-webpack-plugin#498]
## Current behavior
Hello guys, we are using typescript with the webpack setup & for type checking we decided to use `fork-ts-checker-webpack-plugin` and application is running within docker container. As far as we add new changes to the code I see the following in a logs

<img width="1011" alt="Screen Shot 2020-08-07 at 21 41 52" src="https://user-images.githubusercontent.com/37310604/89678548-0d9b6c00-d8f8-11ea-8001-81512158e064.png">

## Steps to reproduce the issue
webpack config part related to `fork-ts-checker-webpack-plugin`
```
new ForkTsCheckerWebpackPlugin({
    eslint: { enabled: true, files: 'src', options: { extensions: ['ts', 'tsx'] } },
}),

...
{
  test: /\.ts?$/,
  exclude: /node_modules/,
  use: [{
     loader: require.resolve('babel-loader'),
     options: { plugins: [require.resolve('react-refresh/babel')] },
   }],
},
```

Dockerfile
```
FROM node:12-alpine
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
CMD ["yarn", "start"]
```

## Environment
 - **fork-ts-checker-webpack-plugin**: ^5.0.14
 - **typescript**: ^3.9.7
 - **eslint**: ^7.6.0
 - **webpack**: ^4.44.1

**Comment by n8vccn** [comment]
Getting same error with same setup on a macOS, any ideas?

**Comment by piotr-oles** [comment]
Thanks for reporting this issue. Could you provide a reproduction repository?

**Comment by jsbroks** [comment]
I'm getting the same error, not really sure how to reproduce tho

**Comment by n8vccn** [comment]
@piotr-oles could it be due to lack of RAM for docker? Cuz I increased it up to 4 Gb and I don't have this error anymore

**Comment by piotr-oles** [comment]
That's may be the case. I have some logic to handle out-of-memory but maybe there is some edge-case when it doesn't work properly.

**Comment by rybkowskigrzegorz** [comment]
I have same issue, definitely it cannot be connected with lack of memory - tested on macOS 32GB RAM

**Comment by filippolcr** [comment]
Same issue with Nuxt 2.12 in Typescript with macOS Catalina 10.15.7

If additional infos are needed, I'm at your disposal.
``` 
ERROR  Error: No handler found for procedure getIssues.                 
15:06:56Error: No handler found for procedure getIssues.
    at Object.<anonymous> (/Users/******/Development/*****-website/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/RpcService.js:21:27)
    at Generator.next (<anonymous>)
    at /Users/******/Development/****-website/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/RpcService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/******/Development/****-website/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/RpcService.js:4:12)
    at callListener (/Users/******/Development/****-website/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/RpcService.js:16:39)
    at /Users/******/Development/****-website/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:31:13
    at Set.forEach (<anonymous>)
    at process.handleMessage (/Users/******/Development/****-website/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:30:26)
    at process.emit (node:events:376:20)

[Function: boundDispatch] [Function: boundCommit]                        15:06:59
```

**Comment by piotr-oles** [comment]
I was not able to reproduce it - if someone provides a reproduction repository, I will re-open this issue

**Comment by matzeeable** [comment]
I encounter the same issue and for my case, the issue was caused by a `sudo sysctl fs.aio-max-nr` modification. I have done this modification because I needed to run multiple MySQL databases on my system ([source](https://stackoverflow.com/a/45598111/5506547)). I do not know if this helps you, but perhaps you have changed this in the past, too.

**Comment by Svenmarim** [comment]
For me the issue was with the Typescript package. When using 4.3.5 everything is OK, but when upgrading to 4.4.3 I get the exact same error message.

**Comment by natuan62** [comment]
I got same problem when run project with vue3-cli with `pnpm serve`, edit code and save => pnpm reload and error occurr 

// my package.json

```
  "scripts": {
    "preinstall": "npx only-allow pnpm",
    "serve": "vue-cli-service serve",

// some packages

"vue": "^3.2.37",
"typescript": "4.6.4",
"webpack": "^4.46.0"

```

- Terminal show error

```
40% building 0/1 modules 1 active /Users/anhtuannguyen/Documents/frontend/src/plugins sync /plugin+\.ts$/iError: No handler found for procedure getIssues.
Error: No handler found for procedure getIssues.
    at Object.<anonymous> (/Users/anhtuannguyen/Documents/frontend/node_modules/.pnpm/fork-ts-checker-webpack-plugin@5.2.1_gplzhsecki363wzvnzp4wfrwvi/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/RpcService.js:21:27)
    at Generator.next (<anonymous>)
    at /Users/anhtuannguyen/Documents/frontend/node_modules/.pnpm/fork-ts-checker-webpack-plugin@5.2.1_gplzhsecki363wzvnzp4wfrwvi/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/RpcService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/anhtuannguyen/Documents/frontend/node_modules/.pnpm/fork-ts-checker-webpack-plugin@5.2.1_gplzhsecki363wzvnzp4wfrwvi/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/RpcService.js:4:12)
    at callListener (/Users/anhtuannguyen/Documents/frontend/node_modules/.pnpm/fork-ts-checker-webpack-plugin@5.2.1_gplzhsecki363wzvnzp4wfrwvi/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/RpcService.js:16:39)
    at /Users/anhtuannguyen/Documents/frontend/node_modules/.pnpm/fork-ts-checker-webpack-plugin@5.2.1_gplzhsecki363wzvnzp4wfrwvi/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:31:13
    at Set.forEach (<anonymous>)
    at process.handleMessage (/Users/anhtuannguyen/Documents/frontend/node_modules/.pnpm/fork-ts-checker-webpack-plugin@5.2.1_gplzhsecki363wzvnzp4wfrwvi/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:30:26)
    at process.emit (events.js:400:28)
98% after emitting SizeLimitsPlugin
```

**Comment by AntonioRedondo** [comment]
Just came to say I got the same issue.™️🤷

**Comment by mangoCG** [comment]
I encountered this problem because the configuration in tsconfig.json and the configuration of webpack were repeated, so deleting the duplicate configuration in tsconfig.json solved this problem

**Comment by istvandesign** [comment]
Same problem after upgrading to TypeScript 5.3.3.
