### ISSUE TITLE
Debug Failure. ImportClause [SOLVED]

### ISSUE THREAD

**Issue by DevoidCoding** [TypeStrong/fork-ts-checker-webpack-plugin#54]
I'm running an electron application with webpack 3.6, everything is going well but I still have this error
```
┏ Renderer -------------------

  C:\Users\Devoid\Desktop\VisualCodeTests\projects\wow-client\node_modules\fork-ts-checker-webpack-plugin\lib\service.js:31
          throw error;
          ^

  Error: Debug Failure. ImportClause
      at getDeclarationSpaces (C:\Users\Devoid\Desktop\VisualCodeTests\projects\wow-client\node_modules\typescript\lib\typescript.js:40136:34)
      at checkExportsOnMergedDeclarations (C:\Users\Devoid\Desktop\VisualCodeTests\projects\wow-client\node_modules\typescript\lib\typescript.js:40071:41)
      at checkVariableLikeDeclaration (C:\Users\Devoid\Desktop\VisualCodeTests\projects\wow-client\node_modules\typescript\lib\typescript.js:41142:17)
      at checkVariableDeclaration (C:\Users\Devoid\Desktop\VisualCodeTests\projects\wow-client\node_modules\typescript\lib\typescript.js:41172:20)
      at checkSourceElement (C:\Users\Devoid\Desktop\VisualCodeTests\projects\wow-client\node_modules\typescript\lib\typescript.js:43038:28)
      at Object.forEach (C:\Users\Devoid\Desktop\VisualCodeTests\projects\wow-client\node_modules\typescript\lib\typescript.js:1500:30)
      at checkVariableStatement (C:\Users\Devoid\Desktop\VisualCodeTests\projects\wow-client\node_modules\typescript\lib\typescript.js:41181:16)
      at checkSourceElement (C:\Users\Devoid\Desktop\VisualCodeTests\projects\wow-client\node_modules\typescript\lib\typescript.js:43007:28)
      at Object.forEach (C:\Users\Devoid\Desktop\VisualCodeTests\projects\wow-client\node_modules\typescript\lib\typescript.js:1500:30)
      at checkSourceFileWorker (C:\Users\Devoid\Desktop\VisualCodeTests\projects\wow-client\node_modules\typescript\lib\typescript.js:43125:20)

┗ ----------------------------
```

I don't know where it comes from and I don't know why.

The project is here if you want to test : https://github.com/DevoidCoding/wow-client

**Comment by piotr-oles** [comment]
It looks like error in typescript and the title changed to [SOLVED] so I will close this issue :)
