### ISSUE TITLE
glob pattern string required

### ISSUE THREAD

**Issue by tcastelly** [TypeStrong/fork-ts-checker-webpack-plugin#594]
Hi,

## Current behavior
After update to `v6.2.1` I can't start anymore a VueJS project.

```
TypeError: glob pattern string required
    at Object.minimatch [as default] (/home/tcy/documents/dev/workspaces/minimatch-bug/node_modules/minimatch/minimatch.js:94:11)
    at /home/tcy/documents/dev/workspaces/minimatch-bug/node_modules/fork-ts-checker-webpack-plugin/lib/watch/InclusiveNodeWatchFileSystem.js:15:40
    at /home/tcy/documents/dev/workspaces/minimatch-bug/node_modules/fork-ts-checker-webpack-plugin/lib/watch/InclusiveNodeWatchFileSystem.js:18:59
    at Array.some (<anonymous>)
    at isIgnored (/home/tcy/documents/dev/workspaces/minimatch-bug/node_modules/fork-ts-checker-webpack-plugin/lib/watch/InclusiveNodeWatchFileSystem.js:18:33)
    at /home/tcy/documents/dev/workspaces/minimatch-bug/node_modules/fork-ts-checker-webpack-plugin/lib/watch/InclusiveNodeWatchFileSystem.js:53:90
    at Array.filter (<anonymous>)
    at InclusiveNodeWatchFileSystem.watch (/home/tcy/documents/dev/workspaces/minimatch-bug/node_modules/fork-ts-checker-webpack-plugin/lib/watch/InclusiveNodeWatchFileSystem.js:53:38)
    at Watching.watch (/home/tcy/documents/dev/workspaces/minimatch-bug/node_modules/webpack/lib/Watching.js:114:48)
    at /home/tcy/documents/dev/workspaces/minimatch-bug/node_modules/webpack/lib/Watching.js:101:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/tcy/documents/dev/workspaces/minimatch-bug/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:80:1)
    at AsyncSeriesHook.lazyCompileHook (/home/tcy/documents/dev/workspaces/minimatch-bug/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._done (/home/tcy/documents/dev/workspaces/minimatch-bug/node_modules/webpack/lib/Watching.js:98:28)
    at /home/tcy/documents/dev/workspaces/minimatch-bug/node_modules/webpack/lib/Watching.js:73:19
    at Compiler.emitRecords (/home/tcy/documents/dev/workspaces/minimatch-bug/node_modules/webpack/lib/Compiler.js:499:39)
    at /home/tcy/documents/dev/workspaces/minimatch-bug/node_modules/webpack/lib/Watching.js:54:20
```

## Steps to reproduce the issue
- clone the repo: https://github.com/shenron/minimatch-bug
- `npm ci`
- `npm run serve`

## Environment
 - **fork-ts-checker-webpack-plugin**: 6.1.2
 - **typescript**: 4.2.4
 - **eslint**: 7.24.0
 - **webpack**: 4.0.0
 - **os**: Gnu Linux / ArchLinux

**Comment by piotr-oles** [comment]
Thanks for reporting that, I think I know where the issue is :) As a temporary workaround, please try to overwrite `watchOptions.ignored` field in webpack config to  `/node_modules/`.

**Comment by piotr-oles** [comment]
It looks like vue is passing `ignored: {}` which seems wrong according to the webpack documentation, but I will create an additional check to handle such a case :)

**Comment by tcastelly** [comment]
It works, thank you very much! :)
