### ISSUE TITLE
TypeError thrown when `watchOptions.ignored` is a function

### ISSUE THREAD

**Issue by viridia** [TypeStrong/fork-ts-checker-webpack-plugin#599]
## Current behavior
Webpack allows 'watchOptions.ignored' to be a function. Until recently, this did not cause a problem with fork-ts-checker-webpack-plugin. However, recently it started throwing this exception:

```
/Volumes/w/fe2/src/MadStudioPortal/node_modules/minimatch/minimatch.js:94
    throw new TypeError('glob pattern string required')
    ^

TypeError: glob pattern string required
    at Object.minimatch [as default] (/Volumes/w/fe2/src/MadStudioPortal/node_modules/minimatch/minimatch.js:94:11)
    at /Volumes/w/fe2/src/MadStudioPortal/node_modules/fork-ts-checker-webpack-plugin/lib/watch/InclusiveNodeWatchFileSystem.js:15:40
    at /Volumes/w/fe2/src/MadStudioPortal/node_modules/fork-ts-checker-webpack-plugin/lib/watch/InclusiveNodeWatchFileSystem.js:18:59
    at Array.some (<anonymous>)
    at isIgnored (/Volumes/w/fe2/src/MadStudioPortal/node_modules/fork-ts-checker-webpack-plugin/lib/watch/InclusiveNodeWatchFileSystem.js:18:33)
    at /Volumes/w/fe2/src/MadStudioPortal/node_modules/fork-ts-checker-webpack-plugin/lib/watch/InclusiveNodeWatchFileSystem.js:53:90
    at Array.filter (<anonymous>)
    at InclusiveNodeWatchFileSystem.watch (/Volumes/w/fe2/src/MadStudioPortal/node_modules/fork-ts-checker-webpack-plugin/lib/watch/InclusiveNodeWatchFileSystem.js:53:38)
    at Watching.watch (/Volumes/w/fe2/src/MadStudioPortal/node_modules/webpack/lib/Watching.js:114:48)
    at /Volumes/w/fe2/src/MadStudioPortal/node_modules/webpack/lib/Watching.js:101:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Volumes/w/fe2/src/MadStudioPortal/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:44:1)
    at AsyncSeriesHook.lazyCompileHook (/Volumes/w/fe2/src/MadStudioPortal/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._done (/Volumes/w/fe2/src/MadStudioPortal/node_modules/webpack/lib/Watching.js:98:28)
    at /Volumes/w/fe2/src/MadStudioPortal/node_modules/webpack/lib/Watching.js:73:19
    at Compiler.emitRecords (/Volumes/w/fe2/src/MadStudioPortal/node_modules/webpack/lib/Compiler.js:499:39)
    at /Volumes/w/fe2/src/MadStudioPortal/node_modules/webpack/lib/Watching.js:54:20
```

It appears that the code is expecting this value to be either a string or a regex.

## Expected behavior
Should duplicate the same behavior as webpack - call the function with the name of the file.

## Steps to reproduce the issue
Set watchOptions.ignored to be a function.

## Environment
 - **fork-ts-checker-webpack-plugin**: [6.2.1]
 - **typescript**: [4.1.3]
 - **webpack**: [4.35.2]
 - **os**: [OS X 10.15.7]

**Comment by piotr-oles** [comment]
Please upgrade to at least 6.2.2 - it should not throw an error starting from this version (#595). I create another PR to handle Function types (starting from 6.2.2, they are just ignored)
