### ISSUE TITLE
Error: Debug Failure. False expression.

### ISSUE THREAD

**Issue by rattrayalex** [TypeStrong/fork-ts-checker-webpack-plugin#608]
## Current behavior

```
➜  yarn build
yarn run v1.22.10
$ webpack
Error: Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.emitBuildInfo (/Users/ralex/code/web/node_modules/typescript/lib/typescript.js:107297:22)
    at emitTsBuildInfoFileForBuilderProgram (/Users/ralex/code/web/packages/components/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/reporter/TypeScriptReporter.js:85:25)
    at /Users/ralex/code/web/packages/components/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/reporter/TypeScriptReporter.js:281:37
    at Object.afterProgramCreate (/Users/ralex/code/web/packages/components/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/reporter/ControlledWatchCompilerHost.js:15:17)
    at synchronizeProgram (/Users/ralex/code/web/node_modules/typescript/lib/typescript.js:112808:22)
    at Object.createWatchProgram (/Users/ralex/code/web/node_modules/typescript/lib/typescript.js:112746:9)
    at Object.<anonymous> (/Users/ralex/code/web/packages/components/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/reporter/TypeScriptReporter.js:290:59)
    at Generator.next (<anonymous>)
    at /Users/ralex/code/web/packages/components/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/reporter/TypeScriptReporter.js:8:71
    at new Promise (<anonymous>)
Hash: e227d30820c3b2d629b8
Version: webpack 4.46.0
Time: 47698ms
Built at: 05/08/2021 5:04:29 PM
   Asset      Size  Chunks             Chunk Names
build.js  2.52 MiB    main  [emitted]  main
...elided...
```

I was able to work around this with the following config:

```js
    new ForkTsCheckerWebpackPlugin({
      typescript: {
        configOverwrite: {
          compilerOptions: {
            outFile: null
          }
        }
      }
    })
```

## Expected behavior

It should not error. 

Probably, it should instead silently merge `outFile: null` and perhaps also `outDir: null`…

## Steps to reproduce the issue

The following in a tsconfig may be sufficient, I'm not sure: 
```
"declaration": true,
"noEmit": false,
"emitDeclarationOnly": true,
"outFile": "./dist/index.d.ts",
```

## Environment
 - **fork-ts-checker-webpack-plugin**: `6.2.6`
 - **typescript**: `4.2.4`
 - **eslint**: `6.8.x`
 - **webpack**: `4.46.0`
 - **os**: macOS

**Comment by piotr-oles** [comment]
Could you test it with a regular `tsc --watch --noEmit` command?

**Comment by rattrayalex** [comment]
That command shows these errors:
```
[2:52:51 PM] Starting compilation in watch mode...

tsconfig.json:6:5 - error TS5053: Option 'emitDeclarationOnly' cannot be specified with option 'noEmit'.

6     "noEmit": false,
      ~~~~~~~~

tsconfig.json:7:5 - error TS5053: Option 'emitDeclarationOnly' cannot be specified with option 'noEmit'.

7     "emitDeclarationOnly": true,
      ~~~~~~~~~~~~~~~~~~~~~

[2:53:10 PM] Found 2 errors. Watching for file changes.
```
Without `--noEmit`, the command succeeds.

**Comment by piotr-oles** [comment]
Ok, thanks, it seems to be an issue in the plugin :)

**Comment by rattrayalex** [comment]
Amazing, thank you!

Confirmed working.
