### ISSUE TITLE
Error after updated project to ESLINT 8 from 7.32 -- eslinteporter.js

### ISSUE THREAD

**Issue by jafin** [TypeStrong/fork-ts-checker-webpack-plugin#664]
## Current behavior

Error in compile after updating ESLINT to v8 (from 7.32)
Reverting to 7.32 fixes error.

TypeError: CLIEngine is not a constructor
    at createEsLintReporter (\src\node_modules\fork-ts-checker-webpack-plugin\lib\eslint-reporter\reporter\EsLintReporter.js:22:20)

## Expected behavior
Not error

## Steps to reproduce the issue
```
npm i eslint@v8
```

## Environment
 - **fork-ts-checker-webpack-plugin**: 6.3.4
 - **typescript**: 4.4.3
 - **eslint**: 8.00
 - **webpack**: 5.58.1
 - **os**: Windows 10H2

**Comment by stefpb** [comment]
We agree: after upgrading to eslint 8.0.0 we get this error:
```
[webpack-cli] Error: When you use 'eslint' option, make sure to install 'eslint'.
    at Object.assertEsLintSupport (/var/www/html/assets/.yarn/$$virtual/fork-ts-checker-webpack-plugin-virtual-83c2d9aa94/0/cache/fork-ts-checker-webpack-plugin-npm-6.3.4-64922e60a2-ef5071bd7d.zip/node_modules/fork-ts-checker-webpack-plugin/lib/eslint-reporter/assertEsLintSupport.js:21:15)
    at ForkTsCheckerWebpackPlugin.apply (/var/www/html/assets/.yarn/$$virtual/fork-ts-checker-webpack-plugin-virtual-83c2d9aa94/0/cache/fork-ts-checker-webpack-plugin-npm-6.3.4-64922e60a2-ef5071bd7d.zip/node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.js:57:35)
    at createCompiler (/var/www/html/assets/.yarn/$$virtual/webpack-virtual-f4515eecc0/0/cache/webpack-npm-5.36.2-0b4e83c6c7-221f75148a.zip/node_modules/webpack/lib/webpack.js:74:12)
    at create (/var/www/html/assets/.yarn/$$virtual/webpack-virtual-f4515eecc0/0/cache/webpack-npm-5.36.2-0b4e83c6c7-221f75148a.zip/node_modules/webpack/lib/webpack.js:123:16)
    at webpack (/var/www/html/assets/.yarn/$$virtual/webpack-virtual-f4515eecc0/0/cache/webpack-npm-5.36.2-0b4e83c6c7-221f75148a.zip/node_modules/webpack/lib/webpack.js:131:47)
    at WebpackCLI.f [as webpack] (/var/www/html/assets/.yarn/$$virtual/webpack-virtual-f4515eecc0/0/cache/webpack-npm-5.36.2-0b4e83c6c7-221f75148a.zip/node_modules/webpack/lib/index.js:54:15)
    at WebpackCLI.createCompiler (/var/www/html/assets/.yarn/$$virtual/webpack-cli-virtual-59efbef654/0/cache/webpack-cli-npm-4.9.0-1d93c5fa43-538b6b86e3.zip/node_modules/webpack-cli/lib/webpack-cli.js:2206:23)
    at WebpackCLI.runWebpack (/var/www/html/assets/.yarn/$$virtual/webpack-cli-virtual-59efbef654/0/cache/webpack-cli-npm-4.9.0-1d93c5fa43-538b6b86e3.zip/node_modules/webpack-cli/lib/webpack-cli.js:2336:16)
    at Command.<anonymous> (/var/www/html/assets/.yarn/$$virtual/webpack-cli-virtual-59efbef654/0/cache/webpack-cli-npm-4.9.0-1d93c5fa43-538b6b86e3.zip/node_modules/webpack-cli/lib/webpack-cli.js:1073:13)
    at async Promise.all (index 1)
    at Command.<anonymous> (/var/www/html/assets/.yarn/$$virtual/webpack-cli-virtual-59efbef654/0/cache/webpack-cli-npm-4.9.0-1d93c5fa43-538b6b86e3.zip/node_modules/webpack-cli/lib/webpack-cli.js:1687:7)

script returned exit code 2
```

Is this https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#the-linter-object-has-been-removed helpful?

**Comment by Michael-Tajmajer-Bentley** [comment]
This is happening in all of my projects as well :-(
