### ISSUE TITLE
[Question] Build fails with OOM error: RpcIpcMessagePortClosedError: Process 7709 exited [SIGABRT]

### ISSUE THREAD

**Issue by alexgleason** [TypeStrong/fork-ts-checker-webpack-plugin#724]
## Current behavior

I develop self-hosted social networking software. I've begun converting it to TypeScript, and ever since some users started complaining about failed builds due to OOM issues. See: https://gitlab.com/soapbox-pub/soapbox-fe/-/issues/865

`fork-ts-checker-webpack-plugin` is throwing the error:

```
matty@virbun2:~/projects/soapbox/frontend/scripts$ ./restore_backup 
yarn run v1.22.17
warning ../../../../package.json: No license field
$ npx webpack
Running in production mode
(node:7702) [DEP_WEBPACK_COMPILATION_CACHE] DeprecationWarning: Compilation.cache was removed in favor of Compilation.getCache()
(Use `node --trace-deprecation ...` to show where the warning was created)

<--- Last few GCs --->

[7709:0x6432ac0]    14549 ms: Scavenge 2023.3 (2063.6) -> 2022.8 (2074.4) MB, 12.5 / 0.0 ms  (average mu = 0.660, current mu = 0.380) allocation failure 
[7709:0x6432ac0]    14587 ms: Scavenge 2029.8 (2074.5) -> 2029.0 (2074.8) MB, 7.8 / 0.0 ms  (average mu = 0.660, current mu = 0.380) allocation failure 
[7709:0x6432ac0]    14860 ms: Scavenge 2030.7 (2074.8) -> 2029.9 (2096.3) MB, 266.7 / 0.0 ms  (average mu = 0.660, current mu = 0.380) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09980 node::Abort() [/home/matty/.nvm/versions/node/v16.14.0/bin/node]
 2: 0xa1c235 node::FatalError(char const*, char const*) [/home/matty/.nvm/versions/node/v16.14.0/bin/node]
 3: 0xcf77be v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/matty/.nvm/versions/node/v16.14.0/bin/node]
 4: 0xcf7b37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/matty/.nvm/versions/node/v16.14.0/bin/node]
 5: 0xeaf3d5  [/home/matty/.nvm/versions/node/v16.14.0/bin/node]
 6: 0xebf09d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/matty/.nvm/versions/node/v16.14.0/bin/node]
 7: 0xec1d9e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/matty/.nvm/versions/node/v16.14.0/bin/node]
 8: 0xe832da v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/matty/.nvm/versions/node/v16.14.0/bin/node]
 9: 0x11fc026 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/matty/.nvm/versions/node/v16.14.0/bin/node]
10: 0x15f0a99  [/home/matty/.nvm/versions/node/v16.14.0/bin/node]
/home/matty/projects/soapbox/frontend/soapbox-fe/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:19
        closedError = new RpcIpcMessagePortClosedError_1.RpcIpcMessagePortClosedError(code
                      ^

RpcIpcMessagePortClosedError: Process 7709 exited [SIGABRT].
    at /home/matty/projects/soapbox/frontend/soapbox-fe/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:19:23
    at Generator.next (<anonymous>)
    at /home/matty/projects/soapbox/frontend/soapbox-fe/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/matty/projects/soapbox/frontend/soapbox-fe/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:4:12)
    at ChildProcess.handleExit (/home/matty/projects/soapbox/frontend/soapbox-fe/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:18:42)
    at ChildProcess.emit (node:events:520:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: null,
  signal: 'SIGABRT'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected behavior

The build doesn't fail.

## Steps to reproduce the issue

I haven't been able to reproduce this on my machine, but I thought it was worth raising since several other users have reported it. This is partly a bug report, partly a question. I can't reproduce it, but it appears to be misbehaving.

## Environment
 - **fork-ts-checker-webpack-plugin**: 6.5.0
 - **typescript**: 4.5.5
 - **eslint**: 7.32.0
 - **webpack**: 5.53.0
 - **os**: ???

**Comment by piotr-oles** [comment]
If there is a problem with the memory limit, it's probably a bug in the typescript itself. The plugin simply calls some typescript API and does not have a significant memory footprint.

You can ask people to run `tsc --noEmit` command - if it also fails then we're sure that it's a typescript issue.

**Comment by alexgleason** [comment]
Thank you, that's what I needed to know.
