### ISSUE TITLE
class IssueWebpackError extends webpack_1.default.WebpackError when running `bin/webpack-dev-server`

### ISSUE THREAD

**Issue by reicolee** [TypeStrong/fork-ts-checker-webpack-plugin#756]
## Current behavior
I am currently using `@rails/webpacker `(v5.2.1) to compile my React app with TS
when following the steps [here](https://github.com/rails/webpacker/blob/22ab02b7c84e917f985ecc76f5916d144f43bfbf/docs/typescript.md#optional-adding-compile-time-type-checking), it kept showing me this error after I run `bin/webpack-dev-server`

```
/path/node_modules/fork-ts-checker-webpack-plugin/lib/issue/issue-webpack-error.js:11
class IssueWebpackError extends webpack_1.default.WebpackError {
                                                  ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/path/node_modules/fork-ts-checker-webpack-plugin/lib/issue/issue-webpack-error.js:11:51)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/path/node_modules/fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-get-issues.js:14:31)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
```

has anyone seen this error before?

## Expected behavior
Run without error

## Environment
 - **fork-ts-checker-webpack-plugin**: "^7.2.11"
 - **typescript**: "^4.7.3"
 - **eslint**: "^7.8.1"
 - **webpack**: "4.44.1" (as a peer dependency for webpacker)
 - **os**: [e.g. Ubuntu 19.04]

**Comment by piotr-oles** [comment]
As stated in the README.md, version 7 of this plugin requires webpack ^5.11.0. If you want to use webpack 4, you should downgrade to version 6.
