### ISSUE TITLE
我在jenkins上构建时会出现错误

### ISSUE THREAD

**Issue by 2812848295** [TypeStrong/fork-ts-checker-webpack-plugin#773]
/var/lib/jenkins/workspace/typ-mall-cms/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:19
        closedError = new RpcIpcMessagePortClosedError_1.RpcIpcMessagePortClosedError(code
                      ^

RpcIpcMessagePortClosedError: Process 3720 exited [SIGKILL].
    at /var/lib/jenkins/workspace/typ-mall-cms/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:19:23
    at Generator.next (<anonymous>)
    at /var/lib/jenkins/workspace/typ-mall-cms/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/var/lib/jenkins/workspace/typ-mall-cms/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:4:12)
    at ChildProcess.handleExit (/var/lib/jenkins/workspace/typ-mall-cms/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:18:42)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  code: null,
  signal: 'SIGKILL'
}
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by 2812848295** [comment]
我是jenkins新手，请问通过什么方式可以解决它？

**Comment by 2812848295** [comment]
在本地build是正常的，但是通过jenkins执行的shell命令是报错的

**Comment by vanpipy** [comment]
> 

编译使用的环境是什么配置？比如

* node and npm or yarn version
* jenkins container

**Comment by piotr-oles** [comment]
I'm not an expert on jenkins, but maybe you have some timeout for the job or memory limit that is not sufficient? It looks like jenkins is sending SIGKILL signal to your process which triggers this error.
